theme: jekyll-theme-cayman
title: CaDDN
description: CaDDN is a monocular 3D object detection pipeline that estimates pixel-wise categorical depth distributions, in order to accurately locate information in 3D space.